"use strict";
exports.__esModule = true;
var base_ships_1 = require("./base-ships");
var startfighters_1 = require("./startfighters");
var _ = require("lodash");
console.log(_.pad("typescript examples", 40, "="));
var ship = new base_ships_1.Spacecraft('hyperdrive');
ship.jumpIntoHyperspace();
var falcon = new startfighters_1.MillenniumFalcon();
falcon.jumpIntoHyperspace();
var goodForTheJob = function (ship) { return ship.cargoContainers > 2; };
console.log("Is falcon good for the job? ".concat(goodForTheJob(falcon) ? 'yes' : 'no'));
